# Generated by Django 2.2.4 on 2019-11-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('landmark', models.CharField(blank=True, max_length=180, null=True)),
                ('address', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'LaundryWork',
            },
        ),
    ]
