# Generated by Django 2.2.4 on 2019-11-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrymodel',
            name='address',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='laundrymodel',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laundrymodel',
            name='mobile',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='laundrymodel',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
