# Generated by Django 2.2.4 on 2019-11-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191105_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='laundrymodel',
            name='order_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='laundrymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='laundrymodel',
            name='landmark',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
